### PR TITLE
Added support for is_nil in queries

### PR DESCRIPTION
**Pull request by evadne**
#15 / @rupurt would you be happy to give this a try

### CODE REVIEW

**Comment by rupurt** [comment]
It works perfectly. Thanks @evadne 

https://github.com/fremantle-industries/notified/pull/2

**Comment by evadne** [comment]
@rupurt Great, I’ll cut a release this weekend

**Comment by evadne** [comment]
@rupurt Sorry for the delay. Version 0.1.6 is out on Hex 👌

**Comment by rupurt** [comment]
No worries. Thanks!

**Pull request merged**
